
BADBOY_CCLEANER = {
	"\"<sylvanas community>", -- [1]
	"+10-+15", -- [2]
	"/w für weitere infos", -- [3]
	"10 - 15 keys", -- [4]
	"10-15 keys", -- [5]
	"10er - 15er", -- [6]
	"10er-15er", -- [7]
	"10ner m+", -- [8]
	"15er", -- [9]
	"1xvip", -- [10]
	"3xvip", -- [11]
	"5 mask vision", -- [12]
	"5 masken", -- [13]
	"< gallywix communit", -- [14]
	"< gallywix community>", -- [15]
	"< gallywix comunity>", -- [16]
	"< s y l v a n a s >", -- [17]
	"< s y l v a n a s >||", -- [18]
	"< unity in diversity >", -- [19]
	"<advance>", -- [20]
	"<atlantik-thrall", -- [21]
	"<booty bay bingo buddies", -- [22]
	"<chromie's bc>", -- [23]
	"<chromies bc>", -- [24]
	"<cloud boosting community>", -- [25]
	"<deal with it", -- [26]
	"<enrage>", -- [27]
	"<gallywix>", -- [28]
	"<garona boost community>", -- [29]
	"<garona>", -- [30]
	"<iboost community>", -- [31]
	"<icecrown community>", -- [32]
	"<icecrown>", -- [33]
	"<nova>", -- [34]
	"<prestige>", -- [35]
	"<pro boosting>", -- [36]
	"<pro boosting>wir", -- [37]
	"<rcu>", -- [38]
	"<restless>", -- [39]
	"<sbs>", -- [40]
	"<sylvanas best deal>", -- [41]
	"<sylvanass best deal>", -- [42]
	"<tc>", -- [43]
	"<tilted>", -- [44]
	"<twenty cigs>", -- [45]
	"<uid>", -- [46]
	"<vdo>", -- [47]
	"<{ unity in diversity }>", -- [48]
	"[frei armor stack", -- [49]
	"]<icecrown>", -- [50]
	"^-^ <sylvanas community>", -- [51]
	"anal", -- [52]
	"armorstack", -- [53]
	"begleitet von erfahrenen spielern", -- [54]
	"bestellungen", -- [55]
	"bietet m+", -- [56]
	"boost", -- [57]
	"carapace", -- [58]
	"cbc", -- [59]
	"chromies", -- [60]
	"exploited>", -- [61]
	"gallywix community||m+", -- [62]
	"garona", -- [63]
	"gbc", -- [64]
	"gilde 12m", -- [65]
	"günstig m+ keys", -- [66]
	"hc run pl/lootshare", -- [67]
	"hydra community", -- [68]
	"iboost", -- [69]
	"intime garantie", -- [70]
	"intimegarantie", -- [71]
	"keystone", -- [72]
	"krakenboost", -- [73]
	"level service", -- [74]
	"m+10", -- [75]
	"m+12", -- [76]
	"m+13", -- [77]
	"m+15", -- [78]
	"m+runs", -- [79]
	"masken", -- [80]
	"oblivion", -- [81]
	"oblivion verkauft", -- [82]
	"pro boost", -- [83]
	"pro boosting", -- [84]
	"rabat", -- [85]
	"rabatt", -- [86]
	"rape", -- [87]
	"rio", -- [88]
	"sale", -- [89]
	"sehr günstiger preis", -- [90]
	"sellrun", -- [91]
	"service", -- [92]
	"sonderpreis", -- [93]
	"spitzenpreis", -- [94]
	"sylvanas community", -- [95]
	"top preis", -- [96]
	"twilightcommunity", -- [97]
	"verkauft >>>>", -- [98]
	"vision 5masked fullclear", -- [99]
	"vision full clean", -- [100]
	"vision full clear", -- [101]
	"wir verkaufen", -- [102]
	"wts 5-mask-run", -- [103]
}
